/**
 * Generable — type-safe guided generation using Zod schemas.
 *
 * The `generable()` function is the TypeScript equivalent of Python's
 * `@fm.generable` decorator. It transforms a Zod object schema into
 * a `GenerableSchema` that can be passed to `session.respond()`.
 *
 * Mirrors: GeneratedContent, GenerationID, generable(), and related
 * types from the Python SDK.
 */

import { z, type ZodObject, type ZodRawShape, type ZodTypeAny } from "zod";
import { ManagedObject } from "./ffi/managed-object.js";
import { getNativeBindings } from "./ffi/native.js";
import type { Pointer, FMGeneratedContentRef } from "./ffi/types.js";
import { GenerationSchema, type PropertyMeta } from "./generation-schema.js";
import { GUIDE_META, type GuideMeta, type GuideConstraints, getGuideMeta } from "./generation-guide.js";
import { isZodOptional, unwrapZodType } from "./type-conversion.js";

// --- GenerationID ---

export class GenerationID {
  readonly value: string;

  constructor(value?: string) {
    this.value = value ?? crypto.randomUUID();
  }

  toString(): string {
    return this.value;
  }
}

// --- GeneratedContent ---

/**
 * Represents structured content generated by the model.
 *
 * Provides typed access to generated property values.
 */
export class GeneratedContent {
  private _contentDict: Record<string, unknown>;
  readonly id: GenerationID;
  private _ptr: FMGeneratedContentRef | null;

  constructor(
    contentDict?: Record<string, unknown>,
    id?: GenerationID,
    ptr?: FMGeneratedContentRef,
  ) {
    this._contentDict = contentDict ?? {};
    this.id = id ?? new GenerationID();
    this._ptr = ptr ?? null;
  }

  /** Create from a JSON string. */
  static fromJSON(jsonStr: string): GeneratedContent {
    const parsed = JSON.parse(jsonStr) as Record<string, unknown>;
    return new GeneratedContent(parsed);
  }

  /** Serialize to JSON. */
  toJSON(): string {
    return JSON.stringify(this._contentDict);
  }

  /**
   * Get a typed property value.
   *
   * @example
   * ```ts
   * const name = content.value<string>("name");
   * const age = content.value<number>("age");
   * ```
   */
  value<T = unknown>(forProperty: string): T {
    const val = this._contentDict[forProperty];
    return val as T;
  }

  /** Get the raw content dictionary. */
  get contentDict(): Record<string, unknown> {
    return { ...this._contentDict };
  }

  /** Whether the content is complete (not partially generated). */
  get isComplete(): boolean {
    if (this._ptr) {
      try {
        const native = getNativeBindings();
        return native.FMGeneratedContentIsComplete(this._ptr);
      } catch {
        return true;
      }
    }
    return true;
  }
}

// --- Generable schema type ---

/**
 * A schema produced by `generable()` that can be passed to
 * `session.respond(prompt, { generating: schema })`.
 */
export interface GenerableSchema<T = unknown> {
  /** The Zod schema for validation. */
  zodSchema: ZodObject<ZodRawShape>;
  /** The underlying GenerationSchema (FFI pointer). */
  generationSchema(): GenerationSchema;
  /** Parse generated content into the typed result. */
  parse(content: GeneratedContent): T;
  /** Schema name. */
  name: string;
  /** Schema description. */
  description?: string;
}

// --- generable() factory ---

/**
 * Create a guided generation schema from a Zod object schema.
 *
 * This is the TypeScript equivalent of Python's `@fm.generable` decorator.
 *
 * @example
 * ```ts
 * const Cat = fm.generable(z.object({
 *   name: fm.guide(z.string(), "Cat's name"),
 *   age: fm.guide(z.number().int(), { description: "Age in years", range: [0, 20] }),
 * }), "A cat profile");
 *
 * const cat = await session.respond("Generate a cat named Whiskers", {
 *   generating: Cat,
 * });
 * console.log(cat.name); // typed as string
 * ```
 */
export function generable<T extends ZodRawShape>(
  schema: ZodObject<T>,
  descriptionOrName?: string,
): GenerableSchema<z.infer<ZodObject<T>>> {
  // Derive name from description or generate one
  const name = descriptionOrName ?? `GenerableSchema_${Date.now()}`;
  const description = descriptionOrName;
  const shape = schema.shape;

  // Collect nested generable schemas
  const nestedSchemas: GenerationSchema[] = [];

  // Extract property metadata from guide annotations
  const properties = new Map<string, PropertyMeta>();
  for (const [key, zodType] of Object.entries(shape)) {
    const guideMeta = getGuideMeta(zodType as ZodTypeAny);
    const meta: PropertyMeta = {
      description: guideMeta?.description,
      guides: guideMeta?.constraints ?? {},
    };
    properties.set(key, meta);
  }

  // Cache the GenerationSchema (lazy)
  let _generationSchema: GenerationSchema | null = null;

  return {
    zodSchema: schema,
    name,
    description,

    generationSchema(): GenerationSchema {
      if (!_generationSchema) {
        _generationSchema = new GenerationSchema(
          name,
          shape as ZodRawShape,
          properties,
          nestedSchemas,
          description,
        );
      }
      return _generationSchema;
    },

    parse(content: GeneratedContent): z.infer<ZodObject<T>> {
      // Use the content dict and validate with Zod
      const raw = content.contentDict;
      return schema.parse(raw);
    },
  };
}
